name: macOS Remote Desktop

on:
  workflow_dispatch: # Allows you to trigger this manually

jobs:
  remote-access:
    runs-on: macos-latest
    steps:
      - name: Install and configure zrok
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          sudo sysadminctl -addUser vncuser -fullName "VNC User" -password "YourPassword123!" -admin
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -specifiedUsers
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users vncuser -access -on -privs -all
          brew install zrok
          zrok enable ahHD9lCRm1Qj --headless
          zrok share private --backend-mode tcpTunnel localhost:5900 --headless &
          tail -f /dev/null
